[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.3.1"
authors = ["Alex Morega <alex@grep.ro>"]
repository = "https://github.com/georust/rust-gdal"
documentation = "https://georust.github.io/rust-gdal/"

[dependencies]
error-chain = "0.11"
libc = "0.2"
geo = "0.6"
gdal-sys = { path = "gdal-sys", version = "0.1"}
num-traits = "0.1"
ndarray = "0.11.1"
num = "0.1.41"
byteorder = "1.2.1"

[workspace]
members = ["gdal-sys"]
